<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_link_length" value="0.5"></xacro:property>
    <xacro:property name="base_link_width" value="0.5"></xacro:property>
    <xacro:property name="base_link_height" value="0.2"></xacro:property>
    <xacro:box_link name="base_link" length="${base_link_length}" width="${base_link_width}" height="${base_link_height}"
                    origin_xyz="0 0 ${base_link_height/2.0}" material="grey"></xacro:box_link>
    
    <xacro:property name="shoulder_link_length" value="0.5"></xacro:property>
    <xacro:property name="shoulder_link_radius" value="0.1"></xacro:property>
    <xacro:cylinder_link name="shoulder_link" length="${shoulder_link_length}" radius="${shoulder_link_radius}"
                        origin_xyz="0 0 ${shoulder_link_length/2.0}" material="blue"></xacro:cylinder_link> 

    <xacro:property name="arm_link_length" value="0.6"></xacro:property>
    <xacro:property name="arm_link_radius" value="0.05"></xacro:property>
    <xacro:cylinder_link name="arm_link" length="${arm_link_length}" radius="${arm_link_radius}"
                        origin_xyz="0 0 ${arm_link_length/2.0}" material="grey"></xacro:cylinder_link> 

    <xacro:property name="elbow_link_length" value="0.1"></xacro:property>
    <xacro:property name="elbow_link_radius" value="0.05"></xacro:property>
    <xacro:cylinder_link name="elbow_link" length="${elbow_link_length}" radius="${elbow_link_radius}"
                            origin_xyz="0 0 ${elbow_link_length/2.0}" material="blue"></xacro:cylinder_link> 

    <xacro:property name="forearm_link_length" value="0.5"></xacro:property>
    <xacro:property name="forearm_link_radius" value="0.05"></xacro:property>
    <xacro:cylinder_link name="forearm_link" length="${forearm_link_length}" radius="${forearm_link_radius}"
                            origin_xyz="0 0 ${forearm_link_length/2.0}" material="grey"></xacro:cylinder_link> 

    <xacro:property name="wrist_link_length" value="0.1"></xacro:property>
    <xacro:property name="wrist_link_width" value="0.1"></xacro:property>
    <xacro:property name="wrist_link_height" value="0.05"></xacro:property>
    <xacro:box_link name="wrist_link" length="${wrist_link_length}" width="${wrist_link_width}" height="${wrist_link_height}"
                    origin_xyz="0 0 ${wrist_link_height/2.0}" material="blue"></xacro:box_link>

    <xacro:property name="hand_link_length" value="0.1"></xacro:property>
    <xacro:property name="hand_link_width" value="0.1"></xacro:property>
    <xacro:property name="hand_link_height" value="0.02"></xacro:property>
    <xacro:box_link name="hand_link" length="${hand_link_length}" width="${hand_link_width}" height="${hand_link_height}"
                    origin_xyz="0 0 ${hand_link_height/2.0}" material="grey"></xacro:box_link>

    <link name="tool_link"></link>

    <!-- Joints -->
    <!-- 1 -->
    <joint name="base_shoulder_joint" type="revolute">
        <parent link="base_link"></parent>
        <child link="shoulder_link"></child>
        <origin xyz="0 0 ${base_link_height}" rpy="0 0 0"></origin>
        <axis xyz="0 0 1"></axis>
        <limit effort="100.0" velocity="1.0" lower="-3.14" upper="3.14"></limit>
    </joint>

    <!-- 2 -->
    <joint name="shoulder_arm_joint" type="revolute">
        <parent link="shoulder_link"></parent>
        <child link="arm_link"></child>
        <origin xyz="0 0 ${shoulder_link_length}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
        <limit effort="100.0" velocity="1.0" lower="0.0" upper="2.5"></limit>
    </joint>

    <!-- 3 -->
    <joint name="arm_elbow_joint" type="revolute">
        <parent link="arm_link"></parent>
        <child link="elbow_link"></child>
        <origin xyz="0 0 ${arm_link_length}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
        <limit effort="100.0" velocity="1.0" lower="0.0" upper="2.5"></limit>
    </joint>

    <!-- 4 -->
    <joint name="elbow_forearm_joint" type="revolute">
        <parent link="elbow_link"></parent>
        <child link="forearm_link"></child>
        <origin xyz="0 0 ${elbow_link_length}" rpy="0 0 0"></origin>
        <axis xyz="0 0 1"></axis>
        <limit effort="100.0" velocity="1.0" lower="-3.14" upper="3.14"></limit>
    </joint>

    <!-- 5 -->
    <joint name="forearm_wrist_joint" type="revolute">
        <parent link="forearm_link"></parent>
        <child link="wrist_link"></child>
        <origin xyz="0 0 ${forearm_link_length}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
        <limit effort="100.0" velocity="1.0" lower="-1.57" upper="1.57"></limit>
    </joint>

    <!-- 6 -->
    <joint name="wrist_hand_joint" type="continuous">
        <parent link="wrist_link"></parent>
        <child link="hand_link"></child>
        <origin xyz="0 0 ${wrist_link_height}" rpy="0 0 0"></origin>
        <axis xyz="0 0 1"></axis>
    </joint>

    <!-- 7 -->
    <joint name="hand_tool_joint" type="fixed">
        <parent link="hand_link"></parent>
        <child link="tool_link"></child>
        <origin xyz="0 0 ${hand_link_height}"></origin>
    </joint>

</robot>
