<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="box_link" params="name length width height origin_xyz material">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${length} ${width} ${height}"></box>
                </geometry>
                <origin xyz="${origin_xyz}" rpy="0 0 0"></origin>
                <material name="${material}"></material>
            </visual>
            <collision>
                <geometry>
                    <box size="${length} ${width} ${height}"></box>
                </geometry>
                <origin xyz="${origin_xyz}" rpy="0 0 0"></origin>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="cylinder_link" params="name length radius origin_xyz material">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder length="${length}" radius="${radius}"></cylinder>
                </geometry>
                <origin xyz="${origin_xyz}" rpy="0 0 0"></origin>
                <material name="${material}"></material>
            </visual>
            <!-- use box instead of cylinder for simpler collision computations -->
            <collision>
                <geometry>
                    <box size="${radius*2.0} ${radius*2.0} ${length}"></box>
                </geometry>
                <origin xyz="${origin_xyz}" rpy="0 0 0"></origin>
            </collision>
        </link>
    </xacro:macro>

</robot>
