<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="1.0"></xacro:property>
    <xacro:property name="base_width" value="0.4"></xacro:property>
    <xacro:property name="base_height" value="0.2"></xacro:property>

    <xacro:property name="wheel_radius" value="0.1"></xacro:property>
    <xacro:property name="wheel_length" value="0.05"></xacro:property>


    <material name="green">
        <!--red green blue alpha-->
        <color rgba="0 0.5 0 1"></color>
    </material>

    <material name="blue">
        <!--red green blue alpha-->
        <color rgba="0 0 1 1"></color>
    </material>

    <link name="world"></link>

    <joint name="world_base_joint" type="fixed">
        <parent link="world"></parent>
        <child link="base_link"></child>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"></origin>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <!-- length, width, height-->
                <box size="${base_length} ${base_width} ${base_height}"></box>
            </geometry>
            <!-- xyz = origin of the box-->
            <!-- rpy(rad) = roll(rotation on x) pitch(rotation on y) yaw(rotation on z)-->
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"></origin>
            <material name="green"></material>
        </visual>
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"></origin>
            <material name="blue"></material>
        </visual>
    </link>
    
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"></parent>
        <child link="right_wheel_link"></child>
        <origin xyz="${-base_length/4} -${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"></origin>
            <material name="blue"></material>
        </visual>
    </link>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"></parent>
        <child link="left_wheel_link"></child>
        <origin xyz="${-base_length/4} ${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"></sphere>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>
        </visual>
    </link>

    <joint name="base_caster_wheel_joint" type="revolute">
        <parent link="base_link"></parent>
        <child link="caster_wheel_link"></child>
        <origin xyz="${base_length/3.0} 0 -${wheel_radius/2.0}" rpy="0 0 0"></origin>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"></limit>
        <axis xyz="0 0 1" ></axis>
    </joint>
    
    
</robot>
