name: Build and push Docker image

on:
  # runs on pull requests
  pull_request:
    paths:
    # runs only if the following files are changed
      - 'Dockerfile'
      - '.github/workflows/docker_image.yaml'

  push:
    # runs on push to branches
    branches: 
      - main
    paths:
      # runs only if the following files are changed
      - 'Dockerfile'
      - '.github/workflows/docker_image.yaml'
    
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ros2-humble-ci

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # downloads repo content into the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
