name: Build and push Docker image

on:
  # runs on push to main branch
  push: [main]
  paths:
  # runs only if the following files are changed
    - 'Dockerfile'
    - '.github/workflows/ros-ci.yaml'
  workflow_dispatch:
    # allows manual trigger of the workflow
    
    